version: '2'
services:
  apache:
    build:
      context: .
      dockerfile: build/apache/php-8.1/Dockerfile
    ports:
      - "80:80"
      - "9001:9000" # xdebug
    volumes:
      - ./src:/var/www/html
      - ~/.composer/cache:/var/www/.composer/cache
      - ~/.npm:/var/www/.npm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
#      VIRTUAL_HOST: "example.localhost"
    depends_on:
      - db
    links:
      - db
    networks:
      - <project_name>-network

  db:
    image: mariadb:10.4.13
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    volumes:
      - dbdata:/var/lib/mysql
      - ./backups:/var/tmp/backups
    networks:
      - <project_name>-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - <project_name>-network

networks:
  <project_name>-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
